--- 
abstract: serialize your RSS as JavaScript
author: Brian Cassidy <bricas@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: XML-RSS-JavaScript
no_index: 
  directory: 
    - css
    - inc
    - t
requires: 
  Test::More: 0
  XML::RSS: 1.31
version: 0.61
