---
name: XML-RSS-JavaScript
version: 0.5
author:
  - Brian Cassidy <bricas@cpan.org>
abstract: serialize your RSS as JavaScript
license: perl
requires:
  XML::RSS: 0.9
provides:
  XML::RSS::JavaScript:
    file: lib/XML/RSS/JavaScript.pm
    version: 0.5
generated_by: Module::Build version 0.2611
